// Code generated by protoc-gen-go. DO NOT EDIT.
// source: calculator.proto

package services

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HelloRequest struct {
	Name                 string               `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	CreatedDate          *timestamp.Timestamp `protobuf:"bytes,2,opt,name=created_date,json=createdDate,proto3" json:"created_date,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c686ea360062a8cf, []int{0}
}

func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (m *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(m, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *HelloRequest) GetCreatedDate() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedDate
	}
	return nil
}

type HelloResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloResponse) Reset()         { *m = HelloResponse{} }
func (m *HelloResponse) String() string { return proto.CompactTextString(m) }
func (*HelloResponse) ProtoMessage()    {}
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c686ea360062a8cf, []int{1}
}

func (m *HelloResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloResponse.Unmarshal(m, b)
}
func (m *HelloResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloResponse.Marshal(b, m, deterministic)
}
func (m *HelloResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloResponse.Merge(m, src)
}
func (m *HelloResponse) XXX_Size() int {
	return xxx_messageInfo_HelloResponse.Size(m)
}
func (m *HelloResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HelloResponse proto.InternalMessageInfo

func (m *HelloResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type Person struct {
	Name                 string               `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age                  int32                `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	Weight               float32              `protobuf:"fixed32,3,opt,name=weight,proto3" json:"weight,omitempty"`
	Height               float64              `protobuf:"fixed64,4,opt,name=height,proto3" json:"height,omitempty"`
	Active               bool                 `protobuf:"varint,5,opt,name=active,proto3" json:"active,omitempty"`
	PhoneNumber          []string             `protobuf:"bytes,6,rep,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Gender               Gender               `protobuf:"varint,7,opt,name=Gender,proto3,enum=services.Gender" json:"Gender,omitempty"`
	Countries            map[string]string    `protobuf:"bytes,8,rep,name=countries,proto3" json:"countries,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	CreatedDate          *timestamp.Timestamp `protobuf:"bytes,9,opt,name=created_date,json=createdDate,proto3" json:"created_date,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Person) Reset()         { *m = Person{} }
func (m *Person) String() string { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()    {}
func (*Person) Descriptor() ([]byte, []int) {
	return fileDescriptor_c686ea360062a8cf, []int{2}
}

func (m *Person) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person.Unmarshal(m, b)
}
func (m *Person) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person.Marshal(b, m, deterministic)
}
func (m *Person) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person.Merge(m, src)
}
func (m *Person) XXX_Size() int {
	return xxx_messageInfo_Person.Size(m)
}
func (m *Person) XXX_DiscardUnknown() {
	xxx_messageInfo_Person.DiscardUnknown(m)
}

var xxx_messageInfo_Person proto.InternalMessageInfo

func (m *Person) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Person) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *Person) GetWeight() float32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func (m *Person) GetHeight() float64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *Person) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

func (m *Person) GetPhoneNumber() []string {
	if m != nil {
		return m.PhoneNumber
	}
	return nil
}

func (m *Person) GetGender() Gender {
	if m != nil {
		return m.Gender
	}
	return Gender_UNKNOWN
}

func (m *Person) GetCountries() map[string]string {
	if m != nil {
		return m.Countries
	}
	return nil
}

func (m *Person) GetCreatedDate() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedDate
	}
	return nil
}

type FibonacciRequest struct {
	N                    uint32   `protobuf:"varint,1,opt,name=n,proto3" json:"n,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FibonacciRequest) Reset()         { *m = FibonacciRequest{} }
func (m *FibonacciRequest) String() string { return proto.CompactTextString(m) }
func (*FibonacciRequest) ProtoMessage()    {}
func (*FibonacciRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c686ea360062a8cf, []int{3}
}

func (m *FibonacciRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FibonacciRequest.Unmarshal(m, b)
}
func (m *FibonacciRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FibonacciRequest.Marshal(b, m, deterministic)
}
func (m *FibonacciRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FibonacciRequest.Merge(m, src)
}
func (m *FibonacciRequest) XXX_Size() int {
	return xxx_messageInfo_FibonacciRequest.Size(m)
}
func (m *FibonacciRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FibonacciRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FibonacciRequest proto.InternalMessageInfo

func (m *FibonacciRequest) GetN() uint32 {
	if m != nil {
		return m.N
	}
	return 0
}

type FibonacciResponse struct {
	Result               uint32   `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FibonacciResponse) Reset()         { *m = FibonacciResponse{} }
func (m *FibonacciResponse) String() string { return proto.CompactTextString(m) }
func (*FibonacciResponse) ProtoMessage()    {}
func (*FibonacciResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c686ea360062a8cf, []int{4}
}

func (m *FibonacciResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FibonacciResponse.Unmarshal(m, b)
}
func (m *FibonacciResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FibonacciResponse.Marshal(b, m, deterministic)
}
func (m *FibonacciResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FibonacciResponse.Merge(m, src)
}
func (m *FibonacciResponse) XXX_Size() int {
	return xxx_messageInfo_FibonacciResponse.Size(m)
}
func (m *FibonacciResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FibonacciResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FibonacciResponse proto.InternalMessageInfo

func (m *FibonacciResponse) GetResult() uint32 {
	if m != nil {
		return m.Result
	}
	return 0
}

type AverageRequest struct {
	Number               float64  `protobuf:"fixed64,1,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AverageRequest) Reset()         { *m = AverageRequest{} }
func (m *AverageRequest) String() string { return proto.CompactTextString(m) }
func (*AverageRequest) ProtoMessage()    {}
func (*AverageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c686ea360062a8cf, []int{5}
}

func (m *AverageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AverageRequest.Unmarshal(m, b)
}
func (m *AverageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AverageRequest.Marshal(b, m, deterministic)
}
func (m *AverageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AverageRequest.Merge(m, src)
}
func (m *AverageRequest) XXX_Size() int {
	return xxx_messageInfo_AverageRequest.Size(m)
}
func (m *AverageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AverageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AverageRequest proto.InternalMessageInfo

func (m *AverageRequest) GetNumber() float64 {
	if m != nil {
		return m.Number
	}
	return 0
}

type AverageResponse struct {
	Result               float64  `protobuf:"fixed64,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AverageResponse) Reset()         { *m = AverageResponse{} }
func (m *AverageResponse) String() string { return proto.CompactTextString(m) }
func (*AverageResponse) ProtoMessage()    {}
func (*AverageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c686ea360062a8cf, []int{6}
}

func (m *AverageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AverageResponse.Unmarshal(m, b)
}
func (m *AverageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AverageResponse.Marshal(b, m, deterministic)
}
func (m *AverageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AverageResponse.Merge(m, src)
}
func (m *AverageResponse) XXX_Size() int {
	return xxx_messageInfo_AverageResponse.Size(m)
}
func (m *AverageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AverageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AverageResponse proto.InternalMessageInfo

func (m *AverageResponse) GetResult() float64 {
	if m != nil {
		return m.Result
	}
	return 0
}

type SumRequest struct {
	Number               int32    `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SumRequest) Reset()         { *m = SumRequest{} }
func (m *SumRequest) String() string { return proto.CompactTextString(m) }
func (*SumRequest) ProtoMessage()    {}
func (*SumRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c686ea360062a8cf, []int{7}
}

func (m *SumRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SumRequest.Unmarshal(m, b)
}
func (m *SumRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SumRequest.Marshal(b, m, deterministic)
}
func (m *SumRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SumRequest.Merge(m, src)
}
func (m *SumRequest) XXX_Size() int {
	return xxx_messageInfo_SumRequest.Size(m)
}
func (m *SumRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SumRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SumRequest proto.InternalMessageInfo

func (m *SumRequest) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

type SumResponse struct {
	Result               int32    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SumResponse) Reset()         { *m = SumResponse{} }
func (m *SumResponse) String() string { return proto.CompactTextString(m) }
func (*SumResponse) ProtoMessage()    {}
func (*SumResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c686ea360062a8cf, []int{8}
}

func (m *SumResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SumResponse.Unmarshal(m, b)
}
func (m *SumResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SumResponse.Marshal(b, m, deterministic)
}
func (m *SumResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SumResponse.Merge(m, src)
}
func (m *SumResponse) XXX_Size() int {
	return xxx_messageInfo_SumResponse.Size(m)
}
func (m *SumResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SumResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SumResponse proto.InternalMessageInfo

func (m *SumResponse) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

func init() {
	proto.RegisterType((*HelloRequest)(nil), "services.HelloRequest")
	proto.RegisterType((*HelloResponse)(nil), "services.HelloResponse")
	proto.RegisterType((*Person)(nil), "services.Person")
	proto.RegisterMapType((map[string]string)(nil), "services.Person.CountriesEntry")
	proto.RegisterType((*FibonacciRequest)(nil), "services.FibonacciRequest")
	proto.RegisterType((*FibonacciResponse)(nil), "services.FibonacciResponse")
	proto.RegisterType((*AverageRequest)(nil), "services.AverageRequest")
	proto.RegisterType((*AverageResponse)(nil), "services.AverageResponse")
	proto.RegisterType((*SumRequest)(nil), "services.SumRequest")
	proto.RegisterType((*SumResponse)(nil), "services.SumResponse")
}

func init() {
	proto.RegisterFile("calculator.proto", fileDescriptor_c686ea360062a8cf)
}

var fileDescriptor_c686ea360062a8cf = []byte{
	// 532 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0x4f, 0x6f, 0xd3, 0x40,
	0x10, 0xc5, 0xb5, 0x49, 0xed, 0xc6, 0x13, 0x27, 0x84, 0x55, 0x09, 0xc6, 0x1c, 0x6a, 0x2c, 0x10,
	0x46, 0x48, 0x4e, 0x15, 0x24, 0x54, 0x21, 0x2a, 0x01, 0x85, 0xc2, 0x09, 0xa1, 0x2d, 0x27, 0x2e,
	0xd5, 0xc6, 0x19, 0x1c, 0x0b, 0xff, 0x09, 0xf6, 0x3a, 0xa8, 0xdf, 0x80, 0x6f, 0x0d, 0xb2, 0x77,
	0x6d, 0xf7, 0x8f, 0x2f, 0xbd, 0xed, 0xbc, 0x79, 0xfb, 0x9b, 0xe4, 0xcd, 0x1a, 0x66, 0x01, 0x8f,
	0x83, 0x32, 0xe6, 0x22, 0xcb, 0xfd, 0x6d, 0x9e, 0x89, 0x8c, 0x8e, 0x0a, 0xcc, 0x77, 0x51, 0x80,
	0x85, 0x6d, 0x86, 0x98, 0xae, 0x51, 0xe9, 0xf6, 0x61, 0x98, 0x65, 0x61, 0x8c, 0x8b, 0xba, 0x5a,
	0x95, 0x3f, 0x17, 0x22, 0x4a, 0xb0, 0x10, 0x3c, 0xd9, 0x4a, 0x83, 0xcb, 0xc1, 0xfc, 0x82, 0x71,
	0x9c, 0x31, 0xfc, 0x5d, 0x62, 0x21, 0x28, 0x85, 0xbd, 0x94, 0x27, 0x68, 0x11, 0x87, 0x78, 0x06,
	0xab, 0xcf, 0xf4, 0x04, 0xcc, 0x20, 0x47, 0x2e, 0x70, 0x7d, 0xb1, 0xe6, 0x02, 0xad, 0x81, 0x43,
	0xbc, 0xf1, 0xd2, 0xf6, 0x25, 0xdb, 0x6f, 0xd8, 0xfe, 0xf7, 0x86, 0xcd, 0xc6, 0xca, 0xff, 0x91,
	0x0b, 0x74, 0x9f, 0xc3, 0x44, 0x8d, 0x28, 0xb6, 0x59, 0x5a, 0x20, 0x9d, 0x83, 0x9e, 0x63, 0x51,
	0xc6, 0x42, 0x4d, 0x51, 0x95, 0xfb, 0x6f, 0x00, 0xfa, 0x37, 0xcc, 0x8b, 0x2c, 0xed, 0xfd, 0x19,
	0x33, 0x18, 0xf2, 0x50, 0x4e, 0xd7, 0x58, 0x75, 0xac, 0x40, 0x7f, 0x30, 0x0a, 0x37, 0xc2, 0x1a,
	0x3a, 0xc4, 0x1b, 0x30, 0x55, 0x55, 0xfa, 0x46, 0xea, 0x7b, 0x0e, 0xf1, 0x08, 0x53, 0x55, 0xa5,
	0xf3, 0x40, 0x44, 0x3b, 0xb4, 0x34, 0x87, 0x78, 0x23, 0xa6, 0x2a, 0xfa, 0x04, 0xcc, 0xed, 0x26,
	0x4b, 0xf1, 0x22, 0x2d, 0x93, 0x15, 0xe6, 0x96, 0xee, 0x0c, 0x3d, 0x83, 0x8d, 0x6b, 0xed, 0x6b,
	0x2d, 0x51, 0x0f, 0xf4, 0xcf, 0x75, 0xb0, 0xd6, 0xbe, 0x43, 0xbc, 0xe9, 0x72, 0xe6, 0x37, 0x89,
	0xfb, 0x52, 0x67, 0xaa, 0x4f, 0x4f, 0xc0, 0x08, 0xb2, 0x32, 0x15, 0x79, 0x84, 0x85, 0x35, 0x72,
	0x86, 0xde, 0x78, 0x79, 0xd8, 0x99, 0xe5, 0xff, 0xf3, 0x4f, 0x1b, 0xc7, 0xa7, 0x54, 0xe4, 0x97,
	0xac, 0xbb, 0x71, 0x2b, 0x6c, 0xe3, 0x4e, 0x61, 0xdb, 0x6f, 0x61, 0x7a, 0x9d, 0x5d, 0xc5, 0xf6,
	0x0b, 0x2f, 0x55, 0x92, 0xd5, 0x91, 0x1e, 0x80, 0xb6, 0xe3, 0x71, 0x29, 0xa3, 0x34, 0x98, 0x2c,
	0xde, 0x0c, 0x8e, 0x89, 0xeb, 0xc0, 0xec, 0x2c, 0x5a, 0x65, 0x29, 0x0f, 0x82, 0xa8, 0x79, 0x11,
	0x26, 0x90, 0xb4, 0xbe, 0x3d, 0x61, 0x24, 0x75, 0x5f, 0xc2, 0xfd, 0x2b, 0x8e, 0xde, 0x85, 0x4e,
	0xda, 0x85, 0x7a, 0x30, 0x7d, 0xbf, 0xc3, 0x9c, 0x87, 0xd8, 0xc0, 0xe6, 0xa0, 0xab, 0x8c, 0x89,
	0xdc, 0x8c, 0xac, 0xdc, 0x17, 0x70, 0xaf, 0x75, 0xf6, 0x42, 0x49, 0x0b, 0x7d, 0x0a, 0x70, 0x5e,
	0x26, 0xfd, 0x40, 0xad, 0x05, 0x3e, 0x83, 0x71, 0xed, 0xea, 0x85, 0x69, 0x0d, 0x6c, 0xf9, 0x77,
	0x00, 0x70, 0xda, 0x7e, 0x4c, 0xf4, 0x18, 0xb4, 0xfa, 0xa9, 0xd2, 0x79, 0xb7, 0xb1, 0xab, 0x9f,
	0x87, 0xfd, 0xf0, 0x96, 0xae, 0x06, 0x9c, 0x81, 0xd1, 0xe6, 0x42, 0xed, 0xce, 0x75, 0x33, 0x4e,
	0xfb, 0x71, 0x6f, 0x4f, 0x52, 0x8e, 0x08, 0x7d, 0x07, 0xfb, 0x2a, 0x08, 0x6a, 0x75, 0xce, 0xeb,
	0x29, 0xda, 0x8f, 0x7a, 0x3a, 0x92, 0xe0, 0x11, 0xfa, 0x1a, 0x86, 0xe7, 0x65, 0x42, 0x0f, 0x3a,
	0x4f, 0x17, 0x97, 0xfd, 0xe0, 0x86, 0xda, 0xdc, 0x3a, 0x22, 0x1f, 0xcc, 0x1f, 0xe0, 0x2f, 0x9a,
	0xee, 0x4a, 0xaf, 0x1f, 0xda, 0xab, 0xff, 0x01, 0x00, 0x00, 0xff, 0xff, 0xd7, 0x06, 0x52, 0xd2,
	0x6b, 0x04, 0x00, 0x00,
}
